version: '2.1'

services:

  nginx-test:
    image: nginx:1.19.4-alpine
    restart: always
    depends_on:
      - app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.narra-web.rule=Host(`${APP_SITE}`)"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ${APP_ROOT}/test:/usr/share/nginx/html:ro
      - ${APP_ROOT}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  app:
    image: narra
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.narra-dev.rule=Host(`${APP_SITE}`) && Path(`/login`,`/auth`,`/401/`)"
      - "traefik.http.services.narra-dev.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.narra-dev.forwardauth.address=http://${APP_SITE}/auth"
      - "traefik.http.middlewares.narra-dev.forwardauth.authResponseHeaders=X-Username"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      --log.debug --as.my_url ${APP_PROTO}://${APP_SITE} --as.cookie_name narra_dev_token
# For traefik:
#  --as.do401
    environment:
      - AS_TYPE
      - AS_HOST
      - AS_TEAM
      - AS_CLIENT_ID
      - AS_CLIENT_KEY
      - AS_COOKIE_SIGN_KEY
      - AS_COOKIE_CRYPT_KEY
    build:
      context: .
      args:
        - GOLANG_VERSION
        - GOPROXY
