name: GoTest

on:
  push:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Test
        run: go test -v -tags test ./...
